### ISSUE TITLE
能支持gemini api吗？

### ISSUE THREAD

**Issue by oyasumiaiko** [yym68686/Cerebr#3]
能支持gemini api 填上key即用吗？

**Comment by yym68686** [comment]
你好，目前仅支持 OpenAI API。可能不考虑适配 其他 API，因为可以使用中转程序转换为 OpenAI 格式。比如你可以使用 我写的 [uni-api](https://github.com/yym68686/uni-api) 来转换。我本人一直通过 [uni-api](https://github.com/yym68686/uni-api) 使用 Gemini API。
